---
title: "R Notebook"
output: html_notebook
---


I will use these packages:
```{r}
library(bezier)
library(imager)
library(lwgeom)
library(MexBrewer) 
library(sf)
library(tidyverse)
library(truchet)
```

```{r}
## CREATE BASE TILE
#  Define square polygon
tile <- matrix(c(0, 0,
                 0, 1,
                 1, 1,
                 1, 0,
                 0, 0),
               ncol = 2,
               byrow = TRUE)

# Convert coordinates to polygons and then to simple features
tile <- data.frame(geometry = sf::st_polygon(list(tile)) %>%
                     sf::st_sfc()) %>%
  sf::st_as_sf()

## BASE TILE DONE
```

```{r}
t <- seq(0,
         1,
         length=50)

pts_1 <- matrix( c(0, 1/3,
                   1/3, 1/3,
                   1/3, 0),
                 nrow=3,
                 ncol=2,
                 byrow=TRUE
)

pts_2 <- matrix( c(0, 1/2,
                   1/2, 1/2,
                   1/2, 0),
                 nrow=3,
                 ncol=2,
                 byrow=TRUE
)

pts_3 <- matrix( c(0, 1/2,
                   1/2, 1/2,
                   1/2, 0),
                 nrow=3,
                 ncol=2,
                 byrow=TRUE
)

# Compute bezier curve
line_1 <- bezier::bezier(t = t,
                         p = pts_1)

line_2 <- bezier::bezier(t = t,
                         p = pts_2)

# Convert points to line
line_1 <- data.frame(id = 1,
                     geometry = sf::st_linestring(line_1) %>%
                       sf::st_geometry()) %>%
  sf::st_sf()

line_2 <- data.frame(id = 2,
                     geometry = sf::st_linestring(line_2) %>%
                       sf::st_geometry()) %>%
  sf::st_sf()

ggplot() + geom_sf(data = tile) + geom_sf(data=line_1) + geom_sf(data=line_2)

# Split the base tile to give the final tile
tile_1 <- tile %>%
  lwgeom::st_split(st_union(line_1, line_2)) %>%
  sf::st_collection_extract() %>%
  dplyr::mutate(color = c(2, 1, 2))
## ADORNMENTS DONE

ggplot() + geom_sf(data = tile_1, aes(fill = color))
```


```{r}
## CREATE BASE TILE
#  Define square polygon
tile <- matrix(c(0, 0,
                 0, 1,
                 1, 1,
                 1, 0,
                 0, 0),
               ncol = 2,
               byrow = TRUE)

# Convert coordinates to polygons and then to simple features
tile <- data.frame(geometry = sf::st_polygon(list(tile)) %>%
                     sf::st_sfc()) %>%
  sf::st_as_sf()
```


```{r}
## ADORNMENTS
pts <- data.frame(x = c(0, 0, 0, 5/12, 1, 1),
                  y = c(0, 7/12, 1, 1, 1, 0))

# Convert coordinates to points and then to simple features
pts <- pts %>%
  sf::st_as_sf(coords = c("x", "y"))

# Assign constant geometry
sf::st_agr(pts) <- "constant"

# Circle segments
cs <- c(1/3)

# Make lines for first set of buffers
# Create buffers and cast to lines
bfs_1 <- pts[c(1,3, 5,6),] %>%
  dplyr::mutate(r = cs[1],
                geometry = pts[c(1,3, 5,6),] %>%
                  #sf::st_buffer(dist = .data$r) %>%
                  sf::st_buffer(dist = r) %>%
                  #dplyr::pull(.data$geometry)) %>%
                  dplyr::pull(geometry)) %>%
  sf::st_set_agr("constant") %>%
  sf::st_cast(to = "LINESTRING") %>%
  dplyr::select(-r)
#dplyr::select(-.data$r)

# Make lines for second set of buffers
# Create buffers and cast to lines
cs <- c(1/2)
bfs_2 <- pts[c(6),] %>%
  dplyr::mutate(r = cs,
                geometry = pts[c(6),] %>%
                  #sf::st_buffer(dist = .data$r) %>%
                  sf::st_buffer(dist = r) %>%
                  #dplyr::pull(.data$geometry)) %>%
                  dplyr::pull(geometry)) %>%
  sf::st_set_agr("constant") %>%
  sf::st_cast(to = "LINESTRING") %>%
  dplyr::select(-r)
#dplyr::select(-.data$r)

# Make lines for third set of buffers
# Create buffers and cast to lines
cs <- c(2/3)
bfs_3 <- pts[c(6),] %>%
  dplyr::mutate(r = cs,
                geometry = pts[c(6),] %>%
                  #sf::st_buffer(dist = .data$r) %>%
                  sf::st_buffer(dist = r) %>%
                  #dplyr::pull(.data$geometry)) %>%
                  dplyr::pull(geometry)) %>%
  sf::st_set_agr("constant") %>%
  sf::st_cast(to = "LINESTRING") %>%
  dplyr::select(-r)
#dplyr::select(-.data$r)

# Make lines for third set of buffers
# Create buffers and cast to lines
cs <- c(1/12)
bfs_4 <- pts[c(2, 4),] %>%
  dplyr::mutate(r = cs,
                geometry = pts[c(2, 4),] %>%
                  #sf::st_buffer(dist = .data$r) %>%
                  sf::st_buffer(dist = r) %>%
                  #dplyr::pull(.data$geometry)) %>%
                  dplyr::pull(geometry)) %>%
  sf::st_set_agr("constant") %>%
  sf::st_cast(to = "LINESTRING") %>%
  dplyr::select(-r)
#dplyr::select(-.data$r)



# Intersect lines with tile
line_1 <- bfs_1 %>%
  sf::st_intersection(sf::st_geometry(tile))

line_2 <- bfs_2 %>%
  sf::st_intersection(sf::st_geometry(tile))

line_3 <- bfs_3 %>%
  sf::st_intersection(sf::st_geometry(tile))

line_4 <- bfs_4 %>%
  sf::st_intersection(sf::st_geometry(tile))


ggplot() + 
  geom_sf(data = tile) + 
  geom_sf(data = line_1) + 
  geom_sf(data = line_2) + 
  geom_sf(data = line_3) + 
  geom_sf(data = line_4)

# Buffer the lines
bfs_2 <- rbind(line_1 %>%
                 sf::st_buffer(dist = 1/6))

# Set geometry to constant
sf::st_agr(tile) <- "constant"
sf::st_agr(bfs_2) <- "constant"

# Bind BASE TILE with second set of buffers
# dl
tile <- rbind(tile %>%
                sf::st_difference(bfs_2 %>%
                                    sf::st_union()),
              bfs_2 %>%
                dplyr::transmute(color = 2))
## ADORNMENTS DONE
```

```{r}
st_truchet_boutique <- function(x = 0, y = 0, type = "ribbons_1", b = 1/2){
  
  #' Flexible Truchet tiles
  #'
  #' @param x A number with the x coordinate of the center of the tile
  #' @param y A number with the y coordinate of the center of the tile
  #' @param type A single character to designate a type of tile; currently supported options are "ribbons_1", "ribbons_2", "ribbons_3", "ribbons_4"
  #' @param b A number between zero and one that controls the shape of the boundary between the two parts of the tile
  #' @return A list with one or more objects of type \code{sf} representing one or more tiles depending on type
  #' @importFrom rlang .data
  #' @export
  #' @examples
  #' st_truchet_boutique(type = "ribbons_1")
  #' st_truchet_boutique(type = "ribbons_2")
  #' @note For a discussion of variable tiling patterns see: Robert J.Krawczyk (2020) Infinitely Variable Tiling Patterns: From Truchet to Sol LeWitt Revisited, Patterns, 1:5, 1-4, \url{10.1016/j.patter.2020.100084} and
  #' Robert J.Krawczyk (2011) Truchet tilings revisited, Proceedings of ISAMA 2011, 69-77 \url{http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.378.5320&rep=rep1&type=pdf#page=69}
  
  # Validate inputs
  checkmate::assertChoice(type, c("ribbons_1", "ribbons_2", "ribbons_3", "ribbons_4"))
  
  ## CREATE BASE TILE
  #  Define square polygon
  tile <- matrix(c(0, 0,
                   0, 1,
                   1, 1,
                   1, 0,
                   0, 0),
                 ncol = 2,
                 byrow = TRUE)
  
  # Convert coordinates to polygons and then to simple features
  tile <- data.frame(geometry = sf::st_polygon(list(tile)) %>%
                       sf::st_sfc()) %>%
    sf::st_as_sf()
  
  ## BASE TILE DONE
  
  # Tile types
  
  switch(type,
         
         "ribbons_1" ={
           ## ADORNMENTS
           pts <- data.frame(x = c(0, 0, 0, 5/12, 1, 1),
                             y = c(0, 7/12, 1, 1, 1, 0))
           
           # Convert coordinates to points and then to simple features
           pts <- pts %>%
             sf::st_as_sf(coords = c("x", "y"))
           
           # Assign constant geometry
           sf::st_agr(pts) <- "constant"
           
           # Circle segments
           cs <- c(1/3)
           
           # Make lines for first set of buffers
           # Create buffers and cast to lines
           bfs_1 <- pts[c(1,3, 5,6),] %>%
             dplyr::mutate(r = cs[1],
                           geometry = pts[c(1,3, 5,6),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for second set of buffers
           # Create buffers and cast to lines
           cs <- c(1/2)
           bfs_2 <- pts[c(6),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(6),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for third set of buffers
           # Create buffers and cast to lines
           cs <- c(2/3)
           bfs_3 <- pts[c(6),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(6),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for fourth set of buffers
           # Create buffers and cast to lines
           cs <- c(1/12)
           bfs_4 <- pts[c(2, 4),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(2, 4),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Intersect lines with tile
           line_1 <- bfs_1 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_2 <- bfs_2 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_3 <- bfs_3 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_4 <- bfs_4 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           # Set geometry to constant
           sf::st_agr(tile) <- "constant"
           #sf::st_agr(bfs_2) <- "constant"
           
           # Bind BASE TILE with second set of buffers
           tile <- rbind(line_1,
                         line_2,
                         line_3,
                         line_4)
           ## ADORNMENTS DONE
         },
         
         "ribbons_2" ={
           ## ADORNMENTS
           pts <- data.frame(x = c(0, 0, 7/12, 1, 1, 1),
                             y = c(0, 1, 1, 1, 7/12, 0))
           
           # Convert coordinates to points and then to simple features
           pts <- pts %>%
             sf::st_as_sf(coords = c("x", "y"))
           
           # Assign constant geometry
           sf::st_agr(pts) <- "constant"
           
           # Circle segments
           cs <- c(1/3)
           
           # Make lines for first set of buffers
           # Create buffers and cast to lines
           bfs_1 <- pts[c(1, 2, 4, 6),] %>%
             dplyr::mutate(r = cs[1],
                           geometry = pts[c(1, 2, 4, 6),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for second set of buffers
           # Create buffers and cast to lines
           cs <- c(1/2)
           bfs_2 <- pts[c(1),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(1),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for third set of buffers
           # Create buffers and cast to lines
           cs <- c(2/3)
           bfs_3 <- pts[c(1),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(1),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for third set of buffers
           # Create buffers and cast to lines
           cs <- c(1/12)
           bfs_4 <- pts[c(3, 5),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(3, 5),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Intersect lines with tile
           line_1 <- bfs_1 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_2 <- bfs_2 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_3 <- bfs_3 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_4 <- bfs_4 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           # Set geometry to constant
           sf::st_agr(tile) <- "constant"
           #sf::st_agr(bfs_2) <- "constant"
           
           # Bind BASE TILE with second set of buffers
           tile <- rbind(line_1,
                         line_2,
                         line_3,
                         line_4)
           ## ADORNMENTS DONE
         },
         
         "ribbons_3" ={
           ## ADORNMENTS
           pts <- data.frame(x = c(0, 0, 1, 1, 1, 7/12),
                             y = c(0, 1, 1, 5/12, 0, 0))
           
           # Convert coordinates to points and then to simple features
           pts <- pts %>%
             sf::st_as_sf(coords = c("x", "y"))
           
           # Assign constant geometry
           sf::st_agr(pts) <- "constant"
           
           # Circle segments
           cs <- c(1/3)
           
           # Make lines for first set of buffers
           # Create buffers and cast to lines
           bfs_1 <- pts[c(1, 2, 3, 5),] %>%
             dplyr::mutate(r = cs[1],
                           geometry = pts[c(1, 2, 3, 5),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for second set of buffers
           # Create buffers and cast to lines
           cs <- c(1/2)
           bfs_2 <- pts[c(2),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(2),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for third set of buffers
           # Create buffers and cast to lines
           cs <- c(2/3)
           bfs_3 <- pts[c(2),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(2),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for third set of buffers
           # Create buffers and cast to lines
           cs <- c(1/12)
           bfs_4 <- pts[c(4, 6),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(4, 6),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Intersect lines with tile
           line_1 <- bfs_1 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_2 <- bfs_2 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_3 <- bfs_3 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_4 <- bfs_4 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           # Set geometry to constant
           sf::st_agr(tile) <- "constant"
           #sf::st_agr(bfs_2) <- "constant"
           
           # Bind BASE TILE with second set of buffers
           tile <- rbind(line_1,
                         line_2,
                         line_3,
                         line_4)
           ## ADORNMENTS DONE
         },
         
         "ribbons_4" ={
           ## ADORNMENTS
           pts <- data.frame(x = c(0, 0, 0, 1, 1, 7/12),
                             y = c(0, 5/12, 1, 1, 0, 0))
           
           # Convert coordinates to points and then to simple features
           pts <- pts %>%
             sf::st_as_sf(coords = c("x", "y"))
           
           # Assign constant geometry
           sf::st_agr(pts) <- "constant"
           
           # Circle segments
           cs <- c(1/3)
           
           # Make lines for first set of buffers
           # Create buffers and cast to lines
           bfs_1 <- pts[c(1, 3, 4, 5),] %>%
             dplyr::mutate(r = cs[1],
                           geometry = pts[c(1, 3, 4, 5),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for second set of buffers
           # Create buffers and cast to lines
           cs <- c(1/2)
           bfs_2 <- pts[c(3),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(3),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for third set of buffers
           # Create buffers and cast to lines
           cs <- c(2/3)
           bfs_3 <- pts[c(3),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(3),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Make lines for third set of buffers
           # Create buffers and cast to lines
           cs <- c(1/12)
           bfs_4 <- pts[c(2, 6),] %>%
             dplyr::mutate(r = cs,
                           geometry = pts[c(2, 6),] %>%
                             #sf::st_buffer(dist = .data$r) %>%
                             sf::st_buffer(dist = r) %>%
                             #dplyr::pull(.data$geometry)) %>%
                             dplyr::pull(geometry)) %>%
             sf::st_set_agr("constant") %>%
             sf::st_cast(to = "LINESTRING") %>%
             dplyr::select(-r)
           #dplyr::select(-.data$r)
           
           # Intersect lines with tile
           line_1 <- bfs_1 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_2 <- bfs_2 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_3 <- bfs_3 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           line_4 <- bfs_4 %>%
             sf::st_intersection(sf::st_geometry(tile))
           
           # Set geometry to constant
           sf::st_agr(tile) <- "constant"
           #sf::st_agr(bfs_2) <- "constant"
           
           # Bind BASE TILE with second set of buffers
           tile <- rbind(line_1,
                         line_2,
                         line_3,
                         line_4)
           ## ADORNMENTS DONE
         }
  )
  
  # Translate so that the tiles are centered on the point (0, 0)
  tile <- tile %>%
    dplyr::mutate(geometry = sf::st_geometry(tile) + c(-0.5, - 0.5))
  
  ## FINISH TILES
  # position at point (x, y)
  tile <- tile %>%
    dplyr::mutate(geometry = sf::st_geometry(tile) + c(x, y))
  
  ## TILES DONE
  
  return(tile)
}
```

Plot sample tiles:
```{r elemental-tiles}
# Tiles types
tile_types <- data.frame(type = c("ribbons_1", "ribbons_2", "ribbons_3", "ribbons_4")) %>%
  mutate(x = c(1, 2.5, 1, 2.5),
         y = c(2.5, 2.5, 1, 1))

# Elements for assembling the mosaic
x_c <- tile_types$x
y_c <- tile_types$y
type <- as.character(tile_types$type)

pmap_dfr(list(x_c, y_c, type), st_truchet_boutique) %>%
  ggplot() + 
  geom_sf(color = "black",
          size = 2) +
  geom_text(data = tile_types,
            aes(x = x,
                y = y,
                label = c("ribbons_1", "ribbons_2", "ribbons_3", "ribbons_4")),
            nudge_y = 0.6) + 
  scale_fill_distiller(direction = 1) +
  theme_void() +
  theme(legend.position = "none")

# Save plot
ggsave("ribbons-tiles.png",
       width = 5,
       height = 5)
```

Mosaic:
```{r}
x_lim <- c(1, 10)
y_lim <- c(1, 10)

# Polygon
container <- matrix(c(x_lim[1] - 0.5, y_lim[1] - 0.5,
                      x_lim[1] - 0.5, y_lim[2] + 0.5,
                      x_lim[2] + 0.5, y_lim[2] + 0.5,
                      x_lim[2] + 0.5, y_lim[1] - 0.5,
                      x_lim[1] - 0.5, y_lim[1] - 0.5),
                    ncol = 2,
                    byrow = TRUE)

# Convert coordinates to polygons and then to simple features
container <- data.frame(geometry = sf::st_polygon(list(container)) %>%
                          sf::st_sfc()) %>%
  sf::st_as_sf()

# Design mosaic
tile_types <- data.frame(expand.grid(x = x_lim[1]:x_lim[2],
                                     y = y_lim[1]:y_lim[2])) %>%
  mutate(type = sample(c("ribbons_1", "ribbons_2", "ribbons_3", "ribbons_4"),
                       size = n(),
                       replace = TRUE),
         color = "black")

# Elements for assembling the mosaic
x_c <- tile_types$x
y_c <- tile_types$y
type <- as.character(tile_types$type)
color <- as.character(tile_types$color)

# Assemble mosaic and render
pmap_dfr(list(x_c, y_c, type, color), st_truchet_boutique) %>%
  st_union() %>%
  ggplot() + 
  geom_sf(data = container,
          color = "#ffd700",
          fill = "#0057b7",
          size = 1.5) +
  geom_sf(color = "#ffd700",
          size = 0.5) +
  scale_fill_distiller(direction = 1) +
  theme_void() +
  theme(legend.position = "none")

# Save plot
ggsave("ribbons-1.png",
       width = 5,
       height = 5)
```

Mosaic with buffers:
```{r}
x_lim <- c(1, 10)
y_lim <- c(1, 10)

# Polygon
container <- matrix(c(x_lim[1] - 0.55, y_lim[1] - 0.55,
                      x_lim[1] - 0.55, y_lim[2] + 0.55,
                      x_lim[2] + 0.55, y_lim[2] + 0.55,
                      x_lim[2] + 0.55, y_lim[1] - 0.55,
                      x_lim[1] - 0.55, y_lim[1] - 0.55),
                    ncol = 2,
                    byrow = TRUE)

# Convert coordinates to polygons and then to simple features
container <- data.frame(geometry = sf::st_polygon(list(container)) %>%
                          sf::st_sfc()) %>%
  sf::st_as_sf()

# Design mosaic
tile_types <- data.frame(expand.grid(x = x_lim[1]:x_lim[2],
                                     y = y_lim[1]:y_lim[2])) %>%
  mutate(type = sample(c("ribbons_1", "ribbons_2", "ribbons_3", "ribbons_4"),
                       size = n(),
                       replace = TRUE),
         color = "black")

# Elements for assembling the mosaic
x_c <- tile_types$x
y_c <- tile_types$y
type <- as.character(tile_types$type)
color <- as.character(tile_types$color)

# Assemble mosaic and render
mosaic <- pmap_dfr(list(x_c, y_c, type, color), st_truchet_boutique) %>%
  st_union() 

# Assemble mosaic and render
ggplot() + 
  geom_sf(data = container,
          color = "#ffd700",
          fill = "#0057b7",
          size = 3) +
  geom_sf(data = mosaic %>%
            st_buffer(dist = 0.125),
          color = NA,
          fill = "#0057b7") +
  geom_sf(data = mosaic %>%
            st_buffer(dist = 0.075),
          color = NA,
          fill = "#ffd700") +
  geom_sf(data = mosaic,
          color = "#0057b7",
          size = 1) +
  theme_void() +
  theme(legend.position = "none")

# Save plot
ggsave("buffered-ribbons-1.png",
       width = 5,
       height = 5)
```
